import { useState } from "react";
import Layout from "../components/Layout";
import { useQuery } from "@tanstack/react-query";
import { payrollApi } from "../api/payrollApi";
import { profileApi } from "../api/profileApi";
import { QUERY_KEYS } from "../utils/queryKeys";
import { formatZAR, formatDate, exportPDF } from "../utils/helpers";

// ===== Sub-row =====
const PayRow = ({ label, value, highlight }) => (
  <div
    className={`flex justify-between items-center 
                ${highlight ? "bg-blue-50 -mx-5 -mb-5 px-5 py-3 rounded-b-xl" : "py-2 border-b border-gray-100"}`}
  >
    <span className={`text-sm ${highlight ? "text-blue-700 font-semibold" : "text-gray-500"}`}>
      {label}
    </span>
    <strong className={`${highlight ? "text-blue-700 text-base" : "text-gray-900 text-sm"}`}>
      {value}
    </strong>
  </div>
);

function MyPayroll() {
  const [selected, setSelected] = useState(null);

  // ===== Queries =====
  const { data: records, isLoading } = useQuery({
    queryKey: QUERY_KEYS.MY_PAYROLL,
    queryFn: payrollApi.getMyPayroll,
    select: (d) => d.data,
  });

  const { data: profile } = useQuery({
    queryKey: QUERY_KEYS.PROFILE,
    queryFn: profileApi.getProfile,
    select: (d) => d.data,
  });

  const latest = selected ?? records?.[0] ?? null;
  const emp = profile?.employee;

  // ===== PDF export =====
  const handleDownload = (record) => {
    const periodLabel = `${formatDate(record.pay_period_start)} – ${formatDate(record.pay_period_end)}`;
    exportPDF(
      `Payslip — ${emp?.name || "Employee"} — ${periodLabel}`,
      `
        <p><strong>Employee:</strong> ${emp?.name || "—"}</p>
        <p><strong>ID:</strong> ${emp?.employee_id ? `EMP-${String(emp.employee_id).padStart(4, "0")}` : "—"}</p>
        <p><strong>Period:</strong> ${periodLabel}</p>
        <br/>
        <table style="width:100%;font-size:14px">
          <tr><td>Normal Pay</td><td align="right"><strong>${formatZAR(record.normal_pay)}</strong></td></tr>
          <tr><td>Overtime Pay</td><td align="right"><strong>${formatZAR(record.overtime_pay)}</strong></td></tr>
          <tr><td>Holiday Pay</td><td align="right"><strong>${formatZAR(record.holiday_pay)}</strong></td></tr>
          <tr><td>Grave Shift Allowance</td><td align="right"><strong>${formatZAR(record.grave_allowance)}</strong></td></tr>
          <tr style="font-size:16px;border-top:2px solid #006fd6">
            <td><strong>Total Earnings</strong></td>
            <td align="right"><strong>${formatZAR(record.total_pay)}</strong></td>
          </tr>
        </table>
        <br/><p style="color:#98a2b3;font-size:11px">Generated: ${new Date().toLocaleDateString("en-ZA")} — NOC Roster & Claims Management System</p>
      `
    );
  };

  return (
    <Layout>
      <section className="p-6">
        <div className="text-sm text-gray-500 mb-4">Dashboard &gt; My Payroll</div>

        <div className="mb-6">
          <h2 className="text-xl font-semibold">My Payroll</h2>
          <p className="text-gray-500 text-sm">View your payslips and earnings history.</p>
        </div>

        {isLoading ? (
          <p className="text-gray-500 text-sm">Loading payroll records...</p>
        ) : !records?.length ? (
          <div className="text-center py-12 text-gray-500">
            <div className="text-4xl mb-3">💰</div>
            <p className="text-base font-bold mb-1">No payroll records yet</p>
            <p className="text-sm">Your payslips will appear here once payroll is generated by admin.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* ===== Summary Card ===== */}
            <div className="bg-white border border-gray-200 rounded-xl p-5">
              <div className="flex justify-between items-start mb-4">
                <h3 className="text-blue-700 font-semibold">
                  {latest
                    ? `${formatDate(latest.pay_period_start)} – ${formatDate(latest.pay_period_end)}`
                    : "—"}
                </h3>
                {latest && (
                  <button
                    onClick={() => handleDownload(latest)}
                    className="bg-blue-600 text-white px-3 py-1 rounded-md text-xs font-bold hover:bg-blue-700"
                  >
                    ⬇ PDF
                  </button>
                )}
              </div>

              {latest ? (
                <>
                  <PayRow label="Normal Pay" value={formatZAR(latest.normal_pay)} />
                  <PayRow label="Overtime Pay (×1.5)" value={formatZAR(latest.overtime_pay)} />
                  <PayRow label="Holiday Pay" value={formatZAR(latest.holiday_pay)} />
                  <PayRow label="Grave Shift Allowance" value={formatZAR(latest.grave_allowance)} />
                  <PayRow label="Total Earnings" value={formatZAR(latest.total_pay)} highlight />
                </>
              ) : (
                <p className="text-gray-500 text-sm">Select a payslip to view details.</p>
              )}

              {latest && (
                <p className="text-gray-500 text-sm mt-3">
                  Generated: {formatDate(latest.generated_at || latest.createdAt)}
                </p>
              )}
            </div>

            {/* ===== Payslip History ===== */}
            <div className="bg-white border border-gray-200 rounded-xl p-5">
              <h3 className="text-gray-900 font-semibold mb-4">Payslip History</h3>

              {records.map((record) => {
                const isActive = record.payroll_id === latest?.payroll_id;
                return (
                  <div
                    key={record.payroll_id}
                    onClick={() => setSelected(record)}
                    className={`flex justify-between items-center p-3 mb-2 rounded-lg cursor-pointer transition 
                                ${isActive ? "bg-blue-50 border border-blue-600" : "bg-white border border-gray-200"}`}
                  >
                    <div className="flex-1">
                      <strong className="text-sm text-gray-900">
                        {formatDate(record.pay_period_start)} – {formatDate(record.pay_period_end)}
                      </strong>
                      <div className="flex gap-3 mt-1">
                        <span className="text-xs text-gray-500">
                          Normal: {formatZAR(record.normal_pay)}
                        </span>
                        {Number(record.overtime_pay) > 0 && (
                          <span className="text-xs text-orange-600">
                            OT: {formatZAR(record.overtime_pay)}
                          </span>
                        )}
                        {Number(record.holiday_pay) > 0 && (
                          <span className="text-xs text-purple-600">
                            Hol: {formatZAR(record.holiday_pay)}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex flex-col items-end gap-2">
                      <strong className="text-sm text-blue-600">
                        {formatZAR(record.total_pay)}
                      </strong>
                      <button
                        onClick={(e) => { e.stopPropagation(); handleDownload(record); }}
                        className="bg-blue-50 border border-gray-200 rounded-md px-2 py-1 text-xs text-blue-600 font-bold hover:bg-blue-100"
                      >
                        ⬇ PDF
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </section>
    </Layout>
  );
}

export default MyPayroll;